### ISSUE TITLE
Contribute to Drupal.org

### ISSUE THREAD

**Issue by aryashreep** [Coyote6/drupal-7-grapesjs#2]
Hi @Coyote6,

Can you please contribute the module to drupal.org? If you want I can help you with this.

**Comment by Coyote6** [comment]
Cool! I have never contributed a module to Drupal.  I don't have time today, but let me look into it tomorrow and see if I can get it up and running.  I would love help with the project.  Thanks! 

P.S. Also I just updated to my latest version of the module.

**Comment by aryashreep** [comment]
> Cool! I have never contributed a module to Drupal. I don't have time today, but let me look into it tomorrow and see if I can get it up and running. I would love help with the project. Thanks!
> 
> P.S. Also I just updated to my latest version of the module.

If you allow me I can publish this to Drupal.org and add you(coyote6graphx) as "Write to VCS",  "Edit project" and  "Administer maintainers".

Let me know your thoughts on this.

**Comment by Coyote6** [comment]
Hi @aryashreep,

I have it up as a sandbox on Drupal and added you as a maintainer with all access.  (https://www.drupal.org/sandbox/coyote6graphx/3023722)

Should I go ahead with the one time approval process to take it live?

https://drupal.org/projects/grapesjs is Chris McIntosh's (https://www.drupal.org/u/cmcintosh) project so I figured we might have to rename the module to grapesjs_editor before we can take it live.  I am guessing we might be able to get https://drupal.org/projects/grapesjs_editor or something along those lines.  

I know there is a lot to do to it.  Feel free to dive in and make changes.  I will try and help as much as possible, but have my business to run, so I may not always be available.  Thanks!

**Comment by aryashreep** [comment]
> Hi @aryashreep,
> 
> I have it up as a sandbox on Drupal and added you as a maintainer with all access. (https://www.drupal.org/sandbox/coyote6graphx/3023722)
> 
> Should I go ahead with the one time approval process to take it live?
> 
> https://drupal.org/projects/grapesjs is Chris McIntosh's (https://www.drupal.org/u/cmcintosh) project so I figured we might have to rename the module to grapesjs_editor before we can take it live. I am guessing we might be able to get https://drupal.org/projects/grapesjs_editor or something along those lines.
> 
> I know there is a lot to do to it. Feel free to dive in and make changes. I will try and help as much as possible, but have my business to run, so I may not always be available. Thanks!

Hi @Coyote6,

Greeting!
I just check the module page(https://drupal.org/projects/grapesjs) it seems there is no code committed for this module. So we can commit the code for this module.

I will check with Chris McIntos to give us full access.

_Drupal community suggests_
--------------------------------------

> Collaboration rather than competition
The Drupal community holds a strong "collaboration rather than competition" ethos, which values joining forces on improving one awesome project rather than building several sub-standard ones that overwhelm end users with choices. While not outright forbidden, duplicate projects are generally discouraged without good reason (such as a fundamentally different architectural approach). Please remember to search existing modules and themes first before embarking on your quest, or taking over an abandoned project. You could save yourself some time, and earn community karma by helping others! 
https://www.drupal.org/contribute/development

**Comment by aryashreep** [comment]
Hi @Coyote6,

I have discussed with Chris McIntosh. He has given the full access to me. I will also add you to the module with full access.

Can I go ahead and commit the code?

**Comment by Coyote6** [comment]
Absolutely! Thanks.

**Comment by aryashreep** [comment]
Hi @Coyote6,

Congrats!!! [GrapesJS](https://www.drupal.org/project/grapesjs) module is contributed and hosted at Drupal.org. As well you have full access to Maintainers.

Thank you.

**Comment by Coyote6** [comment]
Thanks!  I will try and find time to get the Drupal 8 version up to speed so we have both ports.  Appreciate the help in getting this going.
